const data = [
  {
    id: "0",
    event: "Devoid 2.0",
    flyer: "../assets/obd.jpg",
    date: "21st August, 2023",
    venue: "SG Mall",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    cat: "concert",
    rate: "3.8",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "1",
    event: "Wet Republic",
    flyer: "../assets/jj.jpg",
    date: "2nd September, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "Obodanso",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "2",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "3",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "4",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "5",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "6",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "7",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "8",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "9",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "10",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "11",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "12",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "13",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "14",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "15",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "16",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "17",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "18",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "19",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "20",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "21",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "22",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "23",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "24",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "25",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "26",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "27",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "2.6",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "28",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "29",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "30",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

export default data;
