const data = [
  {
    id: "0",
    event: "Devoid 2.0",
    flyer: "../assets/obd.jpg",
    date: "21st September, 2023",
    venue: "SG Mall",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    cat: "concert",
    rate: "3.8",
    det: "Made of Men Entertainment presents another edition of the Devoid Concert. This year's edition is dubbed Devoid 2.0 and it promises to be a night of fun and excitement.",
  },
  {
    id: "1",
    event: "Wet Republic",
    flyer: "../assets/jj.jpg",
    date: "2nd October, 2023",
    price: "Single GHC 10 || Double GHC 15",
    time: "7:00pm",
    venue: "Mandela's Lounge",
    cat: "concert",
    rate: "2.3",
    det: "Legendary Entertainment is out again with another banga, Wet Republic. This event is going to be the biggest event of the year. Don't miss out.",
  },
  {
    id: "2",
    event: "A Taste of Ireland",
    flyer: "../assets/obd.jpg",
    date: "29th September, 2023",
    price: "Single GHC 50 || Double GHC 80",
    time: "8:00pm",
    venue: "Kumasi City Mall",
    cat: "theatre",
    rate: "2.2",
    det: "Starring dancers from Lord of the Dance & Riverdance alongside a treasure trove of Irish Dancing Champions, A Taste of Ireland delivers the very best talent in the nation. Experience one of the most prominent Irish Dance shows in the world today, A Taste of Ireland combines toe-tapping rhythms with heart-warming emotion to create a contemporary Irish dance showcase that will leave you shouting for more.",
  },
  {
    id: "3",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "concert",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "4",
    event: "High School Football",
    flyer: "../assets/hsf.webp",
    date: "6th September, 2023",
    price: "...",
    time: "8:00am",
    venue: "Accra Sports Stadium",
    cat: "sports",
    rate: "4.5",
    det: "Mustangs @ Warriors The Edgewood (Ashtabula, OH) varsity football team has a home non-conference game vs. Grand Valley Orwell, OH",
  },
  {
    id: "5",
    event: "Osagyefo Criterium",
    flyer: "../assets/obd.jpg",
    date: "21st September, 2023",
    price: "...",
    time: "11:00am",
    venue: "Anita Hotel",
    cat: "concert",
    rate: "2.7",
    det: `The Gladiators Cycling Club (GCC) based in Accra is once again hosting "Osagyefo Criterium race" 2023 dubbed "Dare to Achieve".`,
  },
  {
    id: "6",
    event: "Summer Time In Ghana",
    flyer: "../assets/obd.jpg",
    date: "25th - 30th August, 2023",
    price: "Reservation GHC300",
    time: "8:00am ",
    venue: "Rattray Park, Kumasi",
    cat: "concert",
    rate: "3.9",
    det: "Let's spend a Summer Week in Ghana(Only GHC300 to RSVP Your Spot)",
  },
  {
    id: "7",
    event: "The Monster Mash",
    flyer: "../assets/obd.jpg",
    date: "25th August, 2023",
    price: "GHC 100",
    time: "8:00pm",
    venue: "Devoid Night Club",
    cat: "concert",
    rate: "3.9",
    det: "Experience the best and dopest campus party ever at the Monster Mash! Celebrate with your friends",
  },
  {
    id: "8",
    event: "Campus Base Fridays",
    flyer: "../assets/obd.jpg",
    date: "25th August, 2023",
    price: "....",
    time: "8:00pm",
    venue: "The Basement Bar and Lounge, Kumasi",
    cat: "concert",
    rate: "3.9",
    det: "Campus Base Fridays. Fri, Aug 25. 8PM - Sat 2AM. The Basement Bar and Lounge, Kumasi. upcoming in 2 days. Campus Base Fridays.",
  },
  {
    id: "9",
    event: "The Exclusive All Black Party",
    flyer: "../assets/obd.jpg",
    date: "25th August, 2023",
    price: "GHC 50",
    time: "3:00pm",
    venue: "Ridge Condos, Kumasi",
    cat: "concert",
    rate: "3.9",
    det: "The Exclusive All Black Party. Fri, Aug 25. 3PM - Sat 3AM. Ridge Condos, Kumasi.",
  },
  {
    id: "10",
    event: "The Equalizer 3",
    flyer: "../assets/obd.jpg",
    date: "1st September, 2023",
    price: "Single GHC 20 || Double GHC 120",
    time: "8:00pm",
    venue: "CCB Auditorium, KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "Since giving up his life as a government assassin, Robert McCall finds solace in serving justice on behalf of the oppressed. Now living in Southern Italy, he soon discovers his new friends are under the control of local crime bosses. As events turn deadly, McCall becomes their protector by taking on the mafia.",
  },
  {
    id: "11",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "12",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "13",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "14",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "15",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "16",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "17",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "18",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "19",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "20",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "sports",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "21",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "22",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "23",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "24",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "25",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "26",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "27",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "2.6",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "28",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "29",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "30",
    event: "Vodafone Turn Up",
    flyer: "../assets/obd.jpg",
    date: "29th July, 2023",
    price: "Single GHC 20 || Double GHC 30",
    time: "8:00pm",
    venue: "KNUST",
    cat: "theatre",
    rate: "3.9",
    det: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

export default data;
